sylius_resource:
    resources:
        mango_ceska_posta_balikomaty_plugin.ceska_posta_balikomat:
            driver: doctrine/orm
            classes:
                model: MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Entity\CeskaPostaBalikomat
