parameters:
    ceskaPostaBalikomatyApiUrl: 'http://napostu.cpost.cz/vystupy'
    balikomatyShippingMethodsCodes: ['ceska_posta_balikomat']

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Controller\SyncBranches:
        public: true
        arguments:
            $router: '@router'
            $flashBag: '@session.flash_bag'
            $translator: '@translator'
            $api: '@MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Model\Api\CeskaPostaBalikomatyApiInterface'

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Command\SyncCeskaPostaBalikomatyCommand:
        tags:
            - name: 'console.command'
        arguments:
            $api: '@MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Model\Api\CeskaPostaBalikomatyApiInterface'

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Model\Api\CeskaPostaBalikomatyApiInterface:
        factory: MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Factory\CeskaPostaBalikomatyApiFactory:getCeskaPostaBalikomatyApi

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Model\Api\XmlDownloader: ~

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Factory\CeskaPostaBalikomatyApiFactory:
        arguments:
            $downloader: '@MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Model\Api\XmlDownloader'
            $balikomatRepository: '@mango_ceska_posta_balikomaty_plugin.repository.ceska_posta_balikomat'
            $balikomatFactory: '@mango_ceska_posta_balikomaty_plugin.factory.ceska_posta_balikomat'
            $entityManager: '@doctrine.orm.default_entity_manager'
            $apiUrl: '%ceskaPostaBalikomatyApiUrl%'

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Form\Extension\ShipmentCeskaPostaBalikomatyExtension:
        arguments:
            $shippingMethodsResolver: '@sylius.shipping_methods_resolver'
            $shippingMethodRepository: '@sylius.repository.shipping_method'
            $ceskaPostaBalikomatRepository: '@mango_ceska_posta_balikomaty_plugin.repository.ceska_posta_balikomat'
            $balikovnaClass: '%mango_ceska_posta_balikomaty_plugin.model.ceska_posta_balikomat.class%'
            $translator: '@translator'
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Form\Extension\AdminCeskaPostaBalikomatyShippingMethodExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodType

    MangoSylius\SyliusCeskaPostaBalikomatyPlugin\Model\CeskaPostaBalikomatyShipmentExporter:
        public: true
        arguments:
            $currencyConverter: '@sylius.currency_converter'
            $shippingMethodsCodes: '%balikomatyShippingMethodsCodes%'
        tags:
            - name: mango_sylius.shipment_exporter_type
              type: 'ceskaPostaBalikomaty'
              label: 'Česká Pošta Balíkomaty'
